name: Generate snake animation

on:
  # Toda vez que vocÃª faz commit
  push:
    branches: [ main ]
  
  # Todo pull request
  pull_request:
    branches: [ main ]
  
  # A cada 2 horas
  schedule:
    - cron: "0 */2 * * *"
  
  # Manual
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: generate snake.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: MiguelSerea
          outputs: dist/snake.svg
          
      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
